"""Switch hasted_password to password str

Revision ID: 324a3ef03316
Revises: ff8f9282b56c
Create Date: 2025-02-15 10:51:12.549146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "324a3ef03316"
down_revision: Union[str, None] = "ff8f9282b56c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User",
        "password",
        existing_type=sa.String(length=128),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
