"""User.hashed_password set tullable True

Revision ID: 362af124444e
Revises: 9bc304876402
Create Date: 2025-03-16 14:44:03.247509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "362af124444e"
down_revision: Union[str, None] = "9bc304876402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User", "hashed_password", existing_type=postgresql.BYTEA(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User", "hashed_password", existing_type=postgresql.BYTEA(), nullable=False
    )
    # ### end Alembic commands ###
