"""Created User.email

Revision ID: 9bc304876402
Revises: ceeacc5b99ed
Create Date: 2025-03-16 12:42:52.689950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bc304876402"
down_revision: Union[str, None] = "ceeacc5b99ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("email", sa.String(), nullable=False))
    op.drop_constraint("User_name_key", "User", type_="unique")
    op.create_index(op.f("ix_User_email"), "User", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_User_email"), table_name="User")
    op.create_unique_constraint("User_name_key", "User", ["name"])
    op.drop_column("User", "email")
    # ### end Alembic commands ###
