"""User.avatar_ulr set nullable true

Revision ID: 03dd1a7dc92a
Revises: 324a3ef03316
Create Date: 2025-02-15 10:51:52.095146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03dd1a7dc92a"
down_revision: Union[str, None] = "324a3ef03316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User", "avatar_url", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "User", "avatar_url", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    # ### end Alembic commands ###
