"""Created Project.content column

Revision ID: ceeacc5b99ed
Revises: 8d9862d3d563
Create Date: 2025-03-05 21:20:08.627637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ceeacc5b99ed"
down_revision: Union[str, None] = "8d9862d3d563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Project",
        sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Project", "content")
    # ### end Alembic commands ###
