"""Switch hasted_password to password str

Revision ID: ff8f9282b56c
Revises: bd850b43f5ff
Create Date: 2025-02-15 10:50:10.952087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff8f9282b56c"
down_revision: Union[str, None] = "bd850b43f5ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("password", sa.LargeBinary(length=128), nullable=False)
    )
    op.drop_column("User", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "hashed_password", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("User", "password")
    # ### end Alembic commands ###
